//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3634
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDEV.OpenERP.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMDEV.OpenERP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible d&apos;effectuer une requête. Le système est déjà occupé par une requête précédente.
        /// </summary>
        internal static string ALREADY_BUSY {
            get {
                return ResourceManager.GetString("ALREADY_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant la suppression d&apos;un objet OpenERP.
        /// </summary>
        internal static string ERR_DEL_OBJECT {
            get {
                return ResourceManager.GetString("ERR_DEL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant le chargement des traductions d&apos;un champs.
        /// </summary>
        internal static string ERR_LOAD_TRANSLATE {
            get {
                return ResourceManager.GetString("ERR_LOAD_TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom et type d&apos;objet non spécifié, opération impossible.
        /// </summary>
        internal static string ERR_NOMTYPE_OBJET_OPENERP {
            get {
                return ResourceManager.GetString("ERR_NOMTYPE_OBJET_OPENERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant la lecture d&apos;un champs d&apos;un objet OpenERP.
        /// </summary>
        internal static string ERR_READ_FIELD {
            get {
                return ResourceManager.GetString("ERR_READ_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant la lecture des champs d&apos;un objet .NET.
        /// </summary>
        internal static string ERR_READING_OBJECT {
            get {
                return ResourceManager.GetString("ERR_READING_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant l&apos;enregistrement d&apos;un objet vers OpenERP.
        /// </summary>
        internal static string ERR_SAVE_OBJECT {
            get {
                return ResourceManager.GetString("ERR_SAVE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant la sauvegarde des traductions d&apos;un champs.
        /// </summary>
        internal static string ERR_SAVE_TRANSLATE {
            get {
                return ResourceManager.GetString("ERR_SAVE_TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant la lecture des champs d&apos;un objet OpenERP.
        /// </summary>
        internal static string ERROR_READING_VALUES {
            get {
                return ResourceManager.GetString("ERROR_READING_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de la librairie XMLRPC ou erreur provenant directement du serveur :.
        /// </summary>
        internal static string LIB_XMLRPC {
            get {
                return ResourceManager.GetString("LIB_XMLRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manque de paramètre pour terminer correctement cette fonction..
        /// </summary>
        internal static string MANQUE_PARAM {
            get {
                return ResourceManager.GetString("MANQUE_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur inconnue.
        /// </summary>
        internal static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune adresse de serveur spécifiée. Opération impossible..
        /// </summary>
        internal static string NO_HOST {
            get {
                return ResourceManager.GetString("NO_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le serveur OpenERP n&apos;a pas retourné la liste des langues possibles.
        /// </summary>
        internal static string NO_LANGUAGE {
            get {
                return ResourceManager.GetString("NO_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;êtes pas connecté au service OpenERP.
        /// </summary>
        internal static string NOT_CONNECTED {
            get {
                return ResourceManager.GetString("NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de fichier inconnu, non pris en charge par le serveur OpenERP.
        /// </summary>
        internal static string REPORT_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("REPORT_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout atteind sur la génération du rapport.
        /// </summary>
        internal static string TIMEOUT_REPORT {
            get {
                return ResourceManager.GetString("TIMEOUT_REPORT", resourceCulture);
            }
        }
    }
}
